In [1]:
import numpy as np

In [2]:
m = np.array([[1,2,3] , [4,5,6] , [6,7,8]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [3]:
np.mean(m)

4.666666666666667

In [6]:
11/3

3.6666666666666665

In [4]:
np.mean(m , axis=0)

array([3.66666667, 4.66666667, 5.66666667])

In [5]:
np.mean(m , axis=1)

array([2., 5., 7.])

In [11]:
np.median(m) # 1 ,2 ,3, 4 ,5, 6 ,6 ,7 ,8

5.0

In [12]:
np.median(m , axis=0)

array([4., 5., 6.])

In [13]:
np.median(m , axis=1)

array([2., 5., 7.])

In [14]:
m    

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [15]:
np.var(m)

4.888888888888888

In [16]:
np.var(m , axis=0)

array([4.22222222, 4.22222222, 4.22222222])

In [17]:
np.var(m , axis=1)

array([0.66666667, 0.66666667, 0.66666667])

In [19]:
np.std(m , axis=0)

array([2.05480467, 2.05480467, 2.05480467])

In [20]:
np.std(m , axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [23]:
x = np.array([1,2,3,4,5,6,7,8,9])
y = np.array([9,8,7,6,5,4,3,2,1])
np.cov(x,y)[0,1]

-7.5

In [25]:
np.corrcoef(x,y)[1,0]

-1.0