In [1]:
import numpy as np

In [3]:
# dir(np)

In [5]:
# help(np.vdot)

In [6]:
A = [[1,2,3],[3,4,5],[5,6,7]]
X = np.array(A)

In [7]:
X

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [8]:
X = [[1,2,3],
    [4 ,0,6],
    [7 ,8,9]]

Y = [[9,4, 7],
    [6,5,2],
    [3,2,6]]   
X = np.array(X)
Y = np.array(Y)


In [9]:
X

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [10]:
Y

array([[9, 4, 7],
       [6, 5, 2],
       [3, 2, 6]])

In [11]:
X + Y 

array([[10,  6, 10],
       [10,  5,  8],
       [10, 10, 15]])

In [12]:
type(X)

numpy.ndarray

In [13]:
X.dtype

dtype('int32')

In [15]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.empty([4,3])

array([[1.01997071e-311, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 1.06099790e-312, 3.76231868e+174],
       [4.96827559e-091, 9.76835934e+165, 3.54772999e-062],
       [5.80034986e+170, 3.99910963e+252, 2.12787837e+160]])

In [19]:
arr = np.array([1,2,3,4,5,6,7,8])

In [21]:
arr.shape

(8,)

In [22]:
arr.size

8

In [23]:
len(arr)

8

In [29]:
arr2 = np.arange(1 , 51 , 1)   #np.arange(start , end , step)

In [31]:
arr2.shape[0]

50

In [34]:
m =  arr2.reshape([10,5])

In [39]:
print("number of columns is: " , m.shape[1])
print("number of rows is: " , m.shape[0])

number of columns is:  5
number of rows is:  10


In [42]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [45]:
m[0][0]

1

In [46]:
# m[row , col]
m[0,0]

1

In [47]:
m[0]

array([1, 2, 3, 4, 5])

In [48]:
m[-1]

array([46, 47, 48, 49, 50])

In [54]:
m[ : , :-1]    # m[ start:end , start:end]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24],
       [26, 27, 28, 29],
       [31, 32, 33, 34],
       [36, 37, 38, 39],
       [41, 42, 43, 44],
       [46, 47, 48, 49]])

In [55]:
m[1:-1 , 1:-1]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24],
       [27, 28, 29],
       [32, 33, 34],
       [37, 38, 39],
       [42, 43, 44]])

In [57]:
x = np.zeros((10,10))

In [58]:
x[1:-1 , 1:-1] = 1

In [59]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [67]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [75]:
np.random.randint(1 , 10 , (3,3))    #np.random.randint(start , end , shape)

array([[7, 5, 2],
       [9, 8, 4],
       [5, 9, 5]])

In [79]:
np.random.random((3,3))  # np.random.random(shape)  0 , 1 

array([[0.72121352, 0.58501462, 0.89559599],
       [0.86746302, 0.49077887, 0.04032708],
       [0.16630147, 0.9407215 , 0.12581903]])

In [87]:
np.random.seed(12)
np.random.randint(1 , 10 , (3,3))

array([[7, 2, 3],
       [4, 4, 1],
       [7, 2, 5]])

In [88]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [89]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
np.hstack((a , b ))

array([1, 2, 3, 4, 4, 5, 6, 7])

In [91]:
x = np.vstack((a , b ))

In [92]:
x

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [96]:
a

array([1, 2, 3, 4])

In [98]:
np.vstack((x,a))

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [1, 2, 3, 4]])

In [122]:
import numpy as np
w = np.array([[1,3] , [2,4]])
x = np.array([[2,3] , [4,5]])

In [123]:
w.dot(x)

array([[14, 18],
       [20, 26]])

In [124]:
v = np.array([1,2,3])
m = np.array([[1,2,3] , [2,3,4] , [3,4,5]])
w = v + m 

In [125]:
w

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [127]:
# np.diag(w)

In [106]:
np.tril(w)   # lower

array([[2, 0, 0],
       [3, 5, 0],
       [4, 6, 8]])

In [128]:
np.triu(w) # upper

array([[2, 4, 6],
       [0, 5, 7],
       [0, 0, 8]])

In [129]:
v = np.diag(w)

In [130]:
v

array([2, 5, 8])

In [111]:
np.diag(v)

array([[2, 0, 0],
       [0, 5, 0],
       [0, 0, 8]])

In [132]:
np.identity(3 , dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [134]:
s = 2 
w

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [135]:
s * w

array([[ 4,  8, 12],
       [ 6, 10, 14],
       [ 8, 12, 16]])

In [137]:
w[: , :-1]

array([[2, 4],
       [3, 5],
       [4, 6]])

In [138]:
w

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [139]:
np.trace(w)

15

In [141]:
v = np.array([[1],[2],[3]])

In [142]:
v

array([[1],
       [2],
       [3]])

In [143]:
w

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [144]:
v + w

array([[ 3,  5,  7],
       [ 5,  7,  9],
       [ 7,  9, 11]])

In [145]:
w

array([[2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

In [146]:
w.T

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [147]:
m = np .array([[1,2,3] , [2,3,4] , [3,4,5] , [5,6,7]])

In [148]:
m

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [5, 6, 7]])

In [149]:
m.T

array([[1, 2, 3, 5],
       [2, 3, 4, 6],
       [3, 4, 5, 7]])

In [150]:
help(np.trace)

Help on function trace in module numpy:

trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)
    Return the sum along diagonals of the array.
    
    If `a` is 2-D, the sum along its diagonal with the given offset
    is returned, i.e., the sum of elements ``a[i,i+offset]`` for all i.
    
    If `a` has more than two dimensions, then the axes specified by axis1 and
    axis2 are used to determine the 2-D sub-arrays whose traces are returned.
    The shape of the resulting array is the same as that of `a` with `axis1`
    and `axis2` removed.
    
    Parameters
    ----------
    a : array_like
        Input array, from which the diagonals are taken.
    offset : int, optional
        Offset of the diagonal from the main diagonal. Can be both positive
        and negative. Defaults to 0.
    axis1, axis2 : int, optional
        Axes to be used as the first and second axis of the 2-D sub-arrays
        from which the diagonals should be taken. Defaults are the first two
       

In [151]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [156]:
w = np.array([[1,2,3] , [3,4,5] , [2,2,3]])
np.linalg.det(w)


-2.0

In [157]:
w = np.array([[1,2] , [4,5] ])
np.linalg.det(w)

-2.9999999999999996

In [158]:
m = np.array([[1,2,3] , [3,2,5] , [6,1,7]])

In [159]:
m

array([[1, 2, 3],
       [3, 2, 5],
       [6, 1, 7]])

In [160]:
np.linalg.matrix_rank(m)

2

In [164]:
m = np.array([[1,2] , [3,4]])
n = np.linalg.inv(m)
n

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [162]:
(1/-2) * np.array([[4,-2] , [-3 , 1 ]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [167]:
m.dot(n)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [175]:
z = np.zeros((10,10))

In [196]:
z[0,0] = 1
z[2,4] = 1
z[5,7] = 1
z[6,8] = 1
z[6,7] = 1
z[6,9] = 1
z[7,1] = 1
z

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [197]:
z.size

100

In [198]:
nonzero = np.count_nonzero(z)

In [199]:
nonzero / z.size

0.07

In [200]:
1 - nonzero / z.size

0.9299999999999999

In [201]:
from scipy.sparse import csr_matrix , csc_matrix

In [204]:
x = csr_matrix(z)
print(x)
x.todense()

  (0, 0)	1.0
  (2, 4)	1.0
  (5, 7)	1.0
  (6, 7)	1.0
  (6, 8)	1.0
  (6, 9)	1.0
  (7, 1)	1.0


matrix([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 1., 1.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [203]:
print(csc_matrix(z))

  (0, 0)	1.0
  (7, 1)	1.0
  (2, 4)	1.0
  (5, 7)	1.0
  (6, 7)	1.0
  (6, 8)	1.0
  (6, 9)	1.0


In [205]:
m1 = np.array([1,2,3,4])
m2 = np.array([1,2,0,4])

In [206]:
m1 == m2 

array([ True,  True, False,  True])

In [209]:
m1[m1 == m2 ]

array([1, 2, 4])